name: Daily Task

on:
  schedule:
    - cron: '30 14 * * 1-5'  # Run daily at 9:00 AM IST
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run script
        run: python nse_daily_data_load.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
          NEON_TECH_CONNECTION: ${{ secrets.NEON_TECH_CONNECTION }}
          GROWW_API_KEY: ${{ secrets.GROWW_API_KEY }}
          GROWW_API_SECRET: ${{secrets.GROWW_API_SECRET }}
